version: 2

sources:
  - name: inventory
    database: abstract-plane-366315
    schema: Inventory
    tables:
      - name: inventory_log_hist
      - name: date_dim
      - name: persons
      - name: warehouse_loc
      - name: products

